train_scannet:
	sh scripts/reproduce_train/indoor_quadtree_ds.sh
train_tartanair:
	sh scripts/reproduce_train/tartanair_quadtree_ds.sh
test_scannet:
	sh scripts/reproduce_test/indoor_ds_quadtree.sh
test_tartanair:
	sh scripts/reproduce_test/tartanair_ds_quadtree.sh